### ISSUE TITLE
Update Color Palette

### ISSUE THREAD

**Issue by KateMcCall-Kiley** [uscensusbureau/opportunity#10]
<img width="207" alt="primary 1" src="https://cloud.githubusercontent.com/assets/13965725/13408709/340fb80e-defd-11e5-9a0c-1789e294a95a.png">
<img width="696" alt="primary 2" src="https://cloud.githubusercontent.com/assets/13965725/13408711/34e8e0ac-defd-11e5-9537-c20c9443df60.png">
<img width="254" alt="call" src="https://cloud.githubusercontent.com/assets/13965725/13408712/361711b0-defd-11e5-88c4-b1cc4f8f3a35.png">

**Comment by rossdakin** [comment]
What specifically? I tried to use colors exclusively from the Design Standards.

**Comment by KateMcCall-Kiley** [comment]
Totally - I narrowed to the following within the standards -thoughts?

Primary = [image: Inline image 1][image: Inline image 2]

Accent = [image: Inline image 3]


Call = [image: Inline image 4]

On Mon, Feb 29, 2016 at 4:02 PM, Ross Dakin <notifications@github.com>
wrote:

> What specifically? I tried to use colors exclusively from the Design
> Standards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uscensusbureau/opportunity/issues/10#issuecomment-190389509>
> .
>



-- 
Kate McCall-Kiley
Presidential Innovation Fellow
202.285.8005
www.presidentialinnovationfellows.gov

**Comment by rossdakin** [comment]
I think it makes sense to go case by case, though consistency is a noble
goal!


Ross Dakin
Presidential Innovation Fellow
whitehouse.gov/innovationfellows
(202) 286-0143
ross.dakin@pif.gov

On Mon, Feb 29, 2016 at 4:05 PM, Kate McCall-Kiley <notifications@github.com

**Comment by rossdakin** [comment]
Closing — please open new issues with specific changes.
