### ISSUE TITLE
Add DAP

### ISSUE THREAD

**Issue by KateMcCall-Kiley** [uscensusbureau/opportunity#18]
Google analytics add? 
With the ability to see conversion on Join buttons to slack and click throughs to github.

**Comment by rossdakin** [comment]
Good call.

This was already in place (under the PIF account), but I updated the config to reflect the new domain. Also added you as a collaborator (you should see an email).

We should implement DAP though, as we intend for this to live a while. Retitling this issue to reflect that.

**Comment by KateMcCall-Kiley** [comment]
< script src="/sites/all/modules/contrib/usfedgov_google_analytics/js/Universal-Federated-Analytics-Min.js?agency=DOC" type="text/javascript" id="UA-44450756-1"></script>

**Comment by rossdakin** [comment]
80ecf71604e59e835fcd608ea7e59d853e2cc59c
