### ISSUE TITLE
Social media add?

### ISSUE THREAD

**Issue by KateMcCall-Kiley** [uscensusbureau/opportunity#19]
Whether it is a prompt to tweet from the site or something to connect directly with the flurry of social media activity we're hoping for (especially given neighborland photos and WH instagram takeover)

**Comment by rossdakin** [comment]
I feel like this deserves its own hashtag that we rally around (and promote during the march 7 event).

#Opportunity ?
#OpportunityProject ?

The event is titled "Expanding Opportunity with Open Data" — we probably don't want to drift too far from that. Also don't want a lengthy hashtag (takes up room in tweets).
