### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by rossdakin** [uscensusbureau/opportunity#38]
GitHub Pages does not yet support HTTPS for custom domains (see https://github.com/isaacs/github/issues/156).

This means that https://opportunity.census.gov doesn't work.

Solutions include:
- ignore (not super critical, since user doesn't submit any data)
- wait (rumor has it GitHub Pages will fix this in a few months)
- find a new host (e.g. AWS, cloud.gov, etc.)

I am personally in favor of waiting for GitHub Pages to support HTTPS. This allows us to continue leveraging GitHub Pages for serving this site (which is reliable, fast, and free) at very little risk to the user.

**Comment by greggersh** [comment]
I think HTTPS should be made a priority. Without it, the user's browser has no way of knowing if the site it's talking to is the actual site, or an imposter site. If a user were on a malicious network, the content of the site could be modified to direct users to spoofed, malicious sites that they would trust by virtue of them believing they were linked from a .gov domain. Using HTTPS would prevent this from happening.

I'm not sure waiting for Github is a good idea either. I can't imagine their going to support SSL certificates for custom domains as it's a pretty complex problem for them to solve.

Why not look at hosting on S3 behind a reverse proxy? Or using Federalist from 18F? Even a few small EC2 instances would be better than an unencrypted site.

**Comment by alex** [comment]
A relatively straightforward solution is to put a CDN (e.g. CloudFlare) reverse proxying to the `github.io` URL (that way the reverse proxy target is an `https://` URL). Of course you can do similar with your own nginx instance, etc.

**Comment by konklone** [comment]
There are definitely options. You can use a CDN or web proxy like @alex suggested -- this is what OMB does for https://project-open-data.cio.gov when they use GitHub Pages. They use custom code for that, but CloudFlare should work as well (albeit there will be an unencrypted hop behind the scenes, between CloudFlare and GitHub and/or between GitHub's CDN and their origin).

You can also use an S3 bucket configured for "website mode", fronted by CloudFront -- that's what we use for [analytics.usa.gov](https://analytics.usa.gov) and it is exceptionally cheap, in the single digits of dollars per month. That should be encrypted end-to-end, which is the standard we should expect. You'd just need to handle deployment either manually, or using some other webhook-based path. 

For a long time, 18F has used a small [EC2 instance with webhooks](https://18f.gsa.gov/2014/11/17/taking-control-of-our-website-with-jekyll-and-webhooks/) to auto-compile and deploy 18f.gsa.gov. And yes, 18F also offers [Federalist](https://federalist.18f.gov), which offers HTTPS for custom domains. 

While GitHub may eventually add support for custom domain HTTPS -- and I believe they will -- it's most definitely not worth waiting for that to happen. It's a complex feature for them, and not complex enough for opportunity.census.gov that it's worth waiting.

And for what it's worth, OMB was pretty clear in [M-15-13](https://https.cio.gov) that HTTPS for new sites is expected off the bat going forward. In 2016, it should feel bad to launch a new .gov website using plain HTTP.

**Comment by rossdakin** [comment]
Thanks for all the thoughts!

> In 2016, it should feel bad to launch a new .gov website using plain HTTP.

Yeah, it does. It really, really does.

We talked about this and decided to forego HTTPS for the launch given our compressed timeline. I would love to correct this as soon as we can.

Options:
* the S3/Cloudfront route is great — just need to figure out which AWS account this would be (our contacts at Census didn't have one immediately available)
* Federalist — also sounds great; not sure what it takes to establish this relationship between Census and 18F. [Sounds like](https://federalist-docs.18f.gov/) it would be $750/mo. or so, which isn't awful but doesn't feel like the best use of tax dollars for such a simple site.
* CloudFlare — love them for other (non-USG) projects I've worked on. No idea if USG has a relationship with them. Bummer that the backend would still be insecure.

**Comment by alex** [comment]
The backhaul doesn't have to be insecure, you can have cloudflare proxy to
https://whatever.github.io/site/; I do a similar thing with my personal
site with CloudFlare -> https://mythingy.herokuapp.com/

On Mon, Mar 7, 2016 at 9:15 PM, Ross Dakin <notifications@github.com> wrote:

> Thanks for all the thoughts!
>
> In 2016, it should feel bad to launch a new .gov website using plain HTTP.
>
> Yeah, it does. It really, really does.
>
> We talked about this and decided to forego HTTPS for the launch given our
> compressed timeline. I would love to correct this as soon as we can.
>
> Options:
>
>    - the S3/Cloudfront route is great — just need to figure out which AWS
>    account this would be (our contacts at Census didn't have one immediately
>    available)
>    - Federalist — also sounds great; not sure what it takes to establish
>    this relationship between Census and 18F. Sounds like
>    <https://federalist-docs.18f.gov/> it would be $750/mo. or so, which
>    isn't awful but doesn't feel like the best use of tax dollars for such a
>    simple site.
>    - CloudFlare — love them for other (non-USG) projects I've worked on.
>    No idea if USG has a relationship with them. Bummer that the backend would
>    still be insecure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uscensusbureau/opportunity/issues/38#issuecomment-193558506>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by rossdakin** [comment]
Great point!

**Comment by konklone** [comment]
> The backhaul doesn't have to be insecure, you can have cloudflare proxy to https://whatever.github.io/site/; 

@alex GitHub has confirmed in support staff replies to inquiring users that the hop between their CDN and their origins is not secure -- so even if you can configure CloudFlare properly, there's nothing you can do about the hop after the initial hit to github.io.

> CloudFlare — love them for other (non-USG) projects I've worked on. No idea if USG has a relationship with them. Bummer that the backend would still be insecure.

@rossdakin It's more of a per-agency thing, but FWIW, [the FBI](https://www.fbi.gov) is using them. But like I said above, there's necessarily an insecure hop, caused entirely by GitHub. So I would recommend using them for their primary features (DDoD mitigation, speed, security, etc.) on an already-HTTPS origin, than to add HTTPS to an HTTP site.

**Comment by dlapiduz** [comment]
To be honest, if you have access to cloudfront I'd use that plus Lets Encrypt... that is the easier route IMO.

Shameless plug: https://github.com/dlapiduz/letsencrypt-s3front

**Comment by rossdakin** [comment]
Good idea. I never think to use Cloudfront without S3, but that could totally work.

Or were you suggesting Cloudfront+S3? I've never run Cloudfront in front of GitHub Pages (double CDN, hmm) but it would do the trick, wouldn't it?

**Comment by dlapiduz** [comment]
you can use S3 just for the challenge... you can configure that sort of
routing in cloudfront

**Comment by konklone** [comment]
Running CloudFront in front of GHP would give you the same properties as running CloudFlare in front of  GHP. Encrypted to the user, but not all the way back. You can certainly make a determination that either is fine, but it should be an eyes-wide-open determination and it wouldn't be appropriate for anything sensitive.

Running CloudFront in front of S3 is I think what @dlapiduz was recommending, and is what https://github.com/dlapiduz/letsencrypt-s3front is optimized for.

**Comment by dlapiduz** [comment]
For both CloudFlare and CloudFront you could use the non custom domain as an origin, right? https://uscensusbureau.github.io/opportunity/

**Comment by konklone** [comment]
Yes, but GitHub has an insecure hop inside their systems.

**Comment by rossdakin** [comment]
Quick update:

The site has been moved to Census servers, however as currently configured a cert for `www.census.gov` is being served up, so the state of HTTPS is effectively the same (broken).

We're working with the Census team to use a corrected cert.

**Comment by konklone** [comment]
Just pinging since it's been a couple of months. Happy to talk with any folks at Census, if it's gotten dropped.

**Comment by rossdakin** [comment]
Appears resolved.
