### ISSUE TITLE
Next iteration of above the fold?

### ISSUE THREAD

**Issue by KateMcCall-Kiley** [uscensusbureau/opportunity#39]
- Add call to action buttons in header
- Add gradient from dark blue left top to light blue in bottom right
- Try alternate images
- add flipping tools bar on the left

**Comment by rossdakin** [comment]
Clarence suggested moving the top POTUS quote into the head too — it makes
the case right off the bat. Thoughts?


Ross Dakin
Presidential Innovation Fellow
whitehouse.gov/innovationfellows
(202) 286-0143
ross.dakin@pif.gov

**Comment by KateMcCall-Kiley** [comment]
Could we sit together and try a few of these and see which one we want to
go with? Love the flurry :)

On Wed, Mar 2, 2016 at 4:50 PM, Ross Dakin <notifications@github.com> wrote:

> Clarence suggested moving the top POTUS quote into the head too — it makes
> the case right off the bat. Thoughts?
>
>
> Ross Dakin
> Presidential Innovation Fellow
> whitehouse.gov/innovationfellows
> (202) 286-0143
> ross.dakin@pif.gov
>
> On Wed, Mar 2, 2016 at 4:38 PM, Kate McCall-Kiley <
> notifications@github.com>
> wrote:
>
> >
> > - Add call to action buttons in header
> > - Add gradient from dark blue left top to light blue in bottom right
> > - Try alternate images
> > - add flipping tools bar on the left
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/uscensusbureau/opportunity/issues/39>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uscensusbureau/opportunity/issues/39#issuecomment-191448482>
> .
>



-- 
Kate McCall-Kiley
Presidential Innovation Fellow
202.285.8005
www.presidentialinnovationfellows.gov

**Comment by rossdakin** [comment]
One thought per Aden:

<img width="858" alt="screen shot 2016-03-07 at 9 07 27 am" src="https://cloud.githubusercontent.com/assets/44956/13571607/11da9a46-e444-11e5-8d10-a97bc94e419b.png">
