### ISSUE TITLE
Add Big Join button in centered connect and a background to separate it

### ISSUE THREAD

**Issue by KateMcCall-Kiley** [uscensusbureau/opportunity#6]

**Comment by rossdakin** [comment]
What will the button do when you click it?


Ross Dakin
Presidential Innovation Fellow
whitehouse.gov/innovationfellows
(202) 286-0143
ross.dakin@pif.gov

On Mon, Feb 29, 2016 at 3:41 PM, Kate McCall-Kiley <notifications@github.com

**Comment by KateMcCall-Kiley** [comment]
Sends to Slack group log in/sign up
