### ISSUE TITLE
Change section right below footer to recap sentence and Join button

### ISSUE THREAD

**Issue by KateMcCall-Kiley** [uscensusbureau/opportunity#7]

**Comment by rossdakin** [comment]
Text for the sentence? Button does what?


Ross Dakin
Presidential Innovation Fellow
whitehouse.gov/innovationfellows
(202) 286-0143
ross.dakin@pif.gov

On Mon, Feb 29, 2016 at 3:46 PM, Kate McCall-Kiley <notifications@github.com

**Comment by KateMcCall-Kiley** [comment]
Join button for Slack group, GitHub button for repo. Will finalize sentence when I see it but something like. Because where you start should not determine where you end up.
