### ISSUE TITLE
Move 'Your app here' card to be the first or last in the group?

### ISSUE THREAD

**Issue by KateMcCall-Kiley** [uscensusbureau/opportunity#9]

**Comment by rossdakin** [comment]
It already is last…?


Ross Dakin
Presidential Innovation Fellow
whitehouse.gov/innovationfellows
(202) 286-0143
ross.dakin@pif.gov

On Mon, Feb 29, 2016 at 3:49 PM, Kate McCall-Kiley <notifications@github.com

**Comment by KateMcCall-Kiley** [comment]
Showing up in the middle for me

**Comment by rossdakin** [comment]
c731e14
